---
- hosts: linux
  become: yes
  tasks:
  - name: Create facts directory
    file:
      path: /etc/ansible/facts.d
      recurse: yes
      state: directory
  - name: create the fact script using template
    template:
      src: /root/playbooks/datetime.sh.j2
      dest: /etc/ansible/facts.d/date_time.fact
      mode: 0755
  - name: reload the ansible fact
    setup: filter=ansible_local
  - name: print the local fact
    debug:
      msg: "custom fact is {{ansible_local.date_time}}"
